### ISSUE TITLE
Inconsistent behavior between XorRandom and System.Random

### ISSUE THREAD

**Issue by tsunderu** [kekyo/CenterCLR.XorRandomGenerator#1]
XorRandom have some different behavior than System.Random.
- XorRandom.Next() returns negative value while Random.Next() does not.
- XorRandom.NextDouble() (or XorRandom.Sample()) returns negative value while Random.NextDouble() does not.
- XorRandom.Next(int, int) returns wrong value because of wrong XorRandom.Sample()
  and/or no override for Random.Next(int, int).

**Comment by alamar** [comment]
This makes presented implementation unusable, dangerous and confusing.

Please consider fixing it or delisting from NuGet!

**Comment by kekyo** [comment]
My god!!! Sorry! I forgot this project, I'm trying fixed.
